import 'dart:convert';

import 'package:flutter/services.dart';

import 'models/question.dart';

/// Loads versioned question banks produced by the fs-exam-prep engine.
///
/// Banks live in `assets/banks/` (generated by `tools/generate_banks.py`).
/// Every bank is validated against schema v1 on load — see
/// `docs/CONTRACT.md`. [parseBank] is pure (no asset bundle) so it can be
/// unit-tested without Flutter bindings.
class BankRepository {
  /// Bank assets shipped with the app. Regenerate with tools/generate_banks.py.
  static const List<String> availableBanks = [
    'assets/banks/bank-seed-7.json',
    'assets/banks/bank-seed-42.json',
  ];

  /// Loads and validates a bank asset. Throws [BankFormatException].
  Future<List<Question>> loadBank(
      [String asset = 'assets/banks/bank-seed-7.json']) async {
    final raw = await rootBundle.loadString(asset);
    final payload = jsonDecode(raw) as Map<String, dynamic>;
    return parseBank(payload);
  }
}

/// Validates a decoded bank payload against the v1 contract and returns
/// its questions. Throws [BankFormatException] on any violation.
List<Question> parseBank(Map<String, dynamic> payload) {
  for (final field in [
    'schema_version',
    'generator',
    'engine_version',
    'question_count',
    'questions'
  ]) {
    if (!payload.containsKey(field)) {
      throw BankFormatException('bank is missing field "$field"');
    }
  }
  if (payload['schema_version'] != 1) {
    throw BankFormatException(
        'unsupported bank schema_version ${payload['schema_version']}');
  }
  final rawQuestions = payload['questions'];
  if (rawQuestions is! List) {
    throw const BankFormatException('bank "questions" must be a list');
  }
  if (payload['question_count'] != rawQuestions.length) {
    throw BankFormatException(
        'question_count ${payload['question_count']} != ${rawQuestions.length} questions');
  }
  final seen = <String>{};
  final questions = <Question>[];
  for (var i = 0; i < rawQuestions.length; i++) {
    final item = rawQuestions[i];
    if (item is! Map<String, dynamic>) {
      throw BankFormatException('question at index $i is not an object');
    }
    final question = Question.fromJson(item);
    if (!seen.add(question.qid)) {
      throw BankFormatException('duplicate qid "${question.qid}"');
    }
    questions.add(question);
  }
  return questions;
}
