import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../core/theme/theme_controller.dart';

/// Settings: appearance (system / light / dark) and about.
class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final controller = context.watch<ThemeController>();

    return Scaffold(
      appBar: AppBar(title: const Text('Settings')),
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 720),
          child: ListView(
            padding: const EdgeInsets.all(16),
            children: [
              Text('Appearance', style: theme.textTheme.titleLarge),
              const SizedBox(height: 12),
              // SegmentedButton is the Material 3 control for exclusive
              // choice from a small set — the right widget for theme mode.
              SegmentedButton<ThemeMode>(
                segments: const [
                  ButtonSegment(
                    value: ThemeMode.system,
                    label: Text('System'),
                    icon: Icon(Icons.settings_suggest_outlined),
                  ),
                  ButtonSegment(
                    value: ThemeMode.light,
                    label: Text('Light'),
                    icon: Icon(Icons.light_mode_outlined),
                  ),
                  ButtonSegment(
                    value: ThemeMode.dark,
                    label: Text('Dark'),
                    icon: Icon(Icons.dark_mode_outlined),
                  ),
                ],
                selected: {controller.mode},
                onSelectionChanged: (selection) =>
                    context.read<ThemeController>().setMode(selection.first),
              ),
              const SizedBox(height: 8),
              Text(
                'System follows your phone\u2019s setting. '
                'Your choice is saved on this device.',
                style: theme.textTheme.bodySmall,
              ),
              const SizedBox(height: 24),
              Text('About', style: theme.textTheme.titleLarge),
              const ListTile(
                leading: Icon(Icons.info_outlined),
                title: Text('FS Exam Prep'),
                subtitle: Text('Quiz practice for the NCEES FS exam'),
              ),
              const ListTile(
                leading: Icon(Icons.storage_outlined),
                title: Text('Question bank'),
                subtitle: Text(
                    'Dynamically generated by the fs-exam-prep engine · schema v1'),
              ),
              const ListTile(
                leading: Icon(Icons.lock_outlined),
                title: Text('Version'),
                subtitle: Text('0.1.0 (engine schema v1.0.0)'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
